import ExcelJS from "exceljs";
import { Transaction } from "../types/transaction";
import { format, parseISO } from "date-fns";

// Format date as DD-MM-YYYY (Tally convention)
function formatDate(dateStr: string): string {
  try {
    return format(parseISO(dateStr), "dd-MM-yyyy");
  } catch {
    return dateStr;
  }
}

export async function buildExcel(transactions: Transaction[]): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "LedgerLite";
  wb.created = new Date();

  const ws = wb.addWorksheet("Transactions", {
    views: [{ state: "frozen", ySplit: 1 }],
  });

  // Define columns
  ws.columns = [
    { header: "Date", key: "date", width: 14 },
    { header: "Description", key: "description", width: 40 },
    { header: "Debit", key: "debit", width: 14 },
    { header: "Credit", key: "credit", width: 14 },
    { header: "Category", key: "category", width: 18 },
    { header: "Reference", key: "reference", width: 20 },
    { header: "Account", key: "account", width: 20 },
  ];

  // Style header row
  const headerRow = ws.getRow(1);
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 11 };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF16A34A" }, // brand-600 green
    };
    cell.alignment = { vertical: "middle", horizontal: "center" };
    cell.border = {
      bottom: { style: "thin", color: { argb: "FF15803D" } },
    };
  });
  headerRow.height = 24;

  // Add data rows
  transactions.forEach((t, i) => {
    const row = ws.addRow({
      date: formatDate(t.date),
      description: t.description,
      debit: t.type === "debit" ? t.amount : null,
      credit: t.type === "credit" ? t.amount : null,
      category: t.category,
      reference: t.reference,
      account: t.account,
    });

    // Alternate row shading
    if (i % 2 === 1) {
      row.eachCell((cell) => {
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "FFF9FAFB" },
        };
      });
    }

    // Format currency cells
    ["debit", "credit"].forEach((key) => {
      const cell = row.getCell(key);
      if (cell.value !== null && cell.value !== undefined) {
        cell.numFmt = '₹#,##0.00';
        cell.font = {
          color: {
            argb: key === "debit" ? "FFEF4444" : "FF16A34A",
          },
        };
      }
    });
  });

  // Auto-filter on header
  ws.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: ws.columns.length },
  };

  // Summary sheet
  const summary = wb.addWorksheet("Summary");
  const totalCredit = transactions
    .filter((t) => t.type === "credit")
    .reduce((s, t) => s + t.amount, 0);
  const totalDebit = transactions
    .filter((t) => t.type === "debit")
    .reduce((s, t) => s + t.amount, 0);

  summary.addRow(["Total Transactions", transactions.length]);
  summary.addRow(["Total Credit", totalCredit]);
  summary.addRow(["Total Debit", totalDebit]);
  summary.addRow(["Net Balance", totalCredit - totalDebit]);
  summary.addRow(["Generated by", "LedgerLite"]);
  summary.addRow(["Generated on", new Date().toLocaleDateString("en-IN")]);

  summary.getColumn(1).width = 22;
  summary.getColumn(2).width = 18;
  summary.getColumn(1).eachCell((c) => (c.font = { bold: true }));

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}
